name: corridaapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  vibration: ^1.9.0
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.1
  provider: ^6.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
